Added the install for podman to the manpage hook

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -61,6 +61,12 @@ repos:
     hooks:
       - id: generate-manpages
         name: Generate manpages
-        entry: podman run --rm ($ podman build -q -f Containerfiles/manpage.Containerfile)
+        entry: |
+          if ! command -v podman &> /dev/null
+          then
+              echo "Podman could not be found, installing..."
+              sudo apt-get update && sudo apt-get install -y podman
+          fi
+          podman run --rm $(podman build -q -f Containerfiles/manpage.Containerfile)
         language: system
         files: 'convert2rhel/__init__.py'
